#' Harmonize SPA facility outside-funding sources to four non-exclusive buckets
#'
#' @description
#' `cleanFC_fundingSrc()` reads country-specific SPA outside-funding items
#' (e.g., `v146a`, `v146b`, …), generates **country-level binary flags**
#' (e.g., `funding_moh`, `funding_insurance`, …), and then collapses them to
#' four **non-mutually-exclusive** harmonized indicators with the prefix
#' `funding_h_`:
#'
#' - `funding_h_public`   (government sources: MoH/other ministries/local gov, social security, gov. subsidies to private)
#' - `funding_h_private`  (private insurance, employer reimbursement, user fees/internal revenue)
#' - `funding_h_nonstate` (donors/INGOs, faith-based, community, training colleges, bilateral & multilateral)
#' - `funding_h_other`    (catch-all “Other”)
#'
#' It also adds convenience flags (when questionnaire variables exist):
#' `funding_h_none` (None), `funding_h_dk` (Don’t know), and `funding_h_any` (=1 if not None).
#'
#' @param FCdata A `data.frame`/`tibble` of SPA facility-level records that includes:
#'   - a country/wave code in `v000` (e.g., `"MW6"`, `"AF7"`, `"BD7"`, `"ET8"`, `"HT7"`, `"NM09"`, `"NP8"`, `"TZ7"`),
#'   - outside-funding items `v146a`, `v146b`, … (presence varies by country),
#'   - and (where present) `v146y` (“None”), `v146z` (“Don’t know”).
#'
#' @details
#' The function first maps each country’s `v146*` items to a small set of
#' **country-specific 0/1 flags** (e.g., `funding_moh`, `funding_insurance`,
#' `funding_userFees`, `funding_donorNGO`, `funding_bilateral`, etc.) using the
#' labels embedded in the code. It then aggregates those flags into the four
#' cross-country buckets listed above.
#'
#' **Country nuances handled internally:**
#' - **NP8 (Nepal):** “Local level” (`v146d`) is treated as *public/local government*
#'   for harmonization (added as `funding_localGov` before collapsing).
#' - **HT7 (Haiti):** bilateral and multilateral cooperation are recognized and
#'   folded into `funding_h_nonstate`.
#' - **General:** If a referenced `v146*` item is absent in a country/wave, it is
#'   simply ignored in aggregation.
#'
#' The harmonized buckets are **non-exclusive**: a facility may receive support
#' from multiple source types and thus have multiple `funding_h_* == 1`.
#'
#' @return The input `FCdata` with additional columns:
#' - Country-specific flags (e.g., `funding_moh`, `funding_insurance`, …), as generated by the mapping;
#' - Harmonized buckets: `funding_h_public`, `funding_h_private`,
#'   `funding_h_nonstate`, `funding_h_other`;
#' - Optional convenience flags: `funding_h_none`, `funding_h_dk`, `funding_h_any`.
#'
#' @section Error handling:
#' If `v000` is not one of the supported country/wave codes, the function raises
#' an error noting that the country has not yet been customized. Extend the
#' mapping blocks to add support for new waves.
#'
#' @examples
#' \dontrun{
#' # Minimal usage
#' out <- cleanFC_fundingSrc(FCdata)
#'
#' # Tabulate harmonized coverage (non-exclusive)
#' cols <- c("funding_h_public","funding_h_private","funding_h_nonstate","funding_h_other")
#' sapply(cols, function(x) sum(out[[x]], na.rm = TRUE))
#'
#' # Use in a model (e.g., include multiple funding types as covariates)
#' glm(y ~ funding_h_public + funding_h_private + funding_h_nonstate, data = out, family = binomial())
#' }
#'
#' @seealso
#' - SPA questionnaires/recodes for country-specific meanings of `v146*`.
#' - Your analysis code where these indicators are used as covariates.
#'
#' @export



cleanFC_fundingSrc <- function(FCdata) {
  
  if (FCdata$v000[[1]] %in% "MW6") {
    
    # label variable v146a    "Outside funding:CS Ministry of Health"
    # label variable v146b    "Outside funding:CS Other public ministries"
    # label variable v146c    "Outside funding:CS Medical schemes (insurance)"
    # label variable v146d    "Outside funding:CS Social Security fund"
    # label variable v146e    "Outside funding:CS Reimbursement by employer"
    # label variable v146f    "Outside funding:CS Govt. contribution to private"
    # label variable v146g    "Outside funding:CS Donor agencies/ NGOs"
    # label variable v146h    "Outside funding:CS Faith-based programs"
    # label variable v146i    "Outside funding:CS Community programs"
    # label variable v146x    "Outside funding:Other"
    # label variable v146y    "Outside funding:None"
    # label variable v146z    "Outside funding:Don't know"
    
    FCdata$funding_moh <- ifelse(FCdata$v146a %in% 1, 1, 0)
    FCdata$funding_otherPub <- ifelse(FCdata$v146b %in% 1,1, 0)
    FCdata$funding_insurance <- ifelse(FCdata$v146c %in% 1,1, 0)
    FCdata$funding_socialSecurity <- ifelse(FCdata$v146d %in% 1,1, 0)
    FCdata$funding_employer <- ifelse(FCdata$v146e %in% 1,1, 0)
    FCdata$funding_gov2pvt <- ifelse(FCdata$v146f %in% 1,1, 0)
    FCdata$funding_donorNGO <- ifelse(FCdata$v146g %in% 1,1, 0)
    FCdata$funding_faith <- ifelse(FCdata$v146h %in% 1,1, 0)
    FCdata$funding_community <- ifelse(FCdata$v146i %in% 1,1, 0)
    FCdata$funding_other <- ifelse(FCdata$v146x %in% 1,1, 0)
    # any funding
    FCdata$funding_any <- ifelse(FCdata$v146y %in% 0,1, 0)
    
    FCdata$funding_userFees <- NA
    
  } else if (FCdata$v000[[1]] %in% "AF7") {
    
    # label variable v146a    "Outside funding: Ministry of public health - CS"
    # label variable v146b    "Outside funding:Other public ministries - CS"
    # label variable v146c    "Outside funding:Medical scheme (insurance) - CS"
    # label variable v146d    "Outside funding:Social security fund - CS"
    # label variable v146e    "Outside funding:Reimbursement by emplyoer - CS"
    # label variable v146f    "Outside funding:Govt. contribution to private - CS"
    # label variable v146g    "Outside funding:Donor agencies/NGOs - CS"
    # label variable v146h    "Outside funding:Faith-based - CS"
    # label variable v146i    "Outside funding:Community programs - CS"
    # label variable v146j    "Outside funding:Fees/income from hospitalization - CS"
    # label variable v146x    "Outside funding:Other"
    # label variable v146y    "Outside funding:None"
    # label variable v146z    "Outside funding:Don't know"
    
    FCdata$funding_moh <- ifelse(FCdata$v146a %in% 1, 1, 0)
    FCdata$funding_otherPub <- ifelse(FCdata$v146b %in% 1,1, 0)
    FCdata$funding_insurance <- ifelse(FCdata$v146c %in% 1,1, 0)
    FCdata$funding_socialSecurity <- ifelse(FCdata$v146d %in% 1,1, 0)
    FCdata$funding_employer <- ifelse(FCdata$v146e %in% 1,1, 0)
    FCdata$funding_gov2pvt <- ifelse(FCdata$v146f %in% 1,1, 0)
    FCdata$funding_donorNGO <- ifelse(FCdata$v146g %in% 1,1, 0)
    FCdata$funding_faith <- ifelse(FCdata$v146h %in% 1,1, 0)
    FCdata$funding_community <- ifelse(FCdata$v146i %in% 1,1, 0)
    FCdata$funding_userFees <- ifelse(FCdata$v146j %in% 1,1, 0)
    FCdata$funding_other <- ifelse(FCdata$v146x %in% 1,1, 0)
    # any funding
    FCdata$funding_any <- ifelse(FCdata$v146y %in% 0,1, 0)
    
    
    
  } else if (FCdata$v000[[1]] %in% "BD7") {
    
    # label variable v146a    "Outside funding:CS Ministry of Health"
    # label variable v146b    "Outside funding:CS Other public ministries"
    # label variable v146c    "Outside funding:CS Medical schemes (insurance)"
    # label variable v146d    "Outside funding:CS Social Security fund"
    # label variable v146e    "Outside funding:CS Reimbursement by employer"
    # label variable v146f    "Outside funding:CS Government contribution to private"
    # label variable v146g    "Outside funding:CS Donor agencies/NGOs"
    # label variable v146h    "Outside funding:CS Faith-based organizations"
    # label variable v146i    "Outside funding:CS Community programs"
    # label variable v146j    "Outside funding:CS User Fees"
    # label variable v146x    "Outside funding:Other"
    # label variable v146y    "Outside funding:None"
    # label variable v146z    "Outside funding:Don't know"
    
    FCdata$funding_moh <- ifelse(FCdata$v146a %in% 1, 1, 0)
    FCdata$funding_otherPub <- ifelse(FCdata$v146b %in% 1,1, 0)
    FCdata$funding_insurance <- ifelse(FCdata$v146c %in% 1,1, 0)
    FCdata$funding_socialSecurity <- ifelse(FCdata$v146d %in% 1,1, 0)
    FCdata$funding_employer <- ifelse(FCdata$v146e %in% 1,1, 0)
    FCdata$funding_gov2pvt <- ifelse(FCdata$v146f %in% 1,1, 0)
    FCdata$funding_donorNGO <- ifelse(FCdata$v146g %in% 1,1, 0)
    FCdata$funding_faith <- ifelse(FCdata$v146h %in% 1,1, 0)
    FCdata$funding_community <- ifelse(FCdata$v146i %in% 1,1, 0)
    FCdata$funding_userFees <- ifelse(FCdata$v146j %in% 1,1, 0)
    FCdata$funding_other <- ifelse(FCdata$v146x %in% 1,1, 0)
    # any funding
    FCdata$funding_any <- ifelse(FCdata$v146y %in% 0,1, 0)
    
  } else if (FCdata$v000[[1]] %in% "ET8") {
    
    # label variable v146a    "Outside funding: CS Ministry of Health"
    # label variable v146b    "Outside funding: CS Other public ministries"
    # label variable v146c    "Outside funding: CS Medical schemes (insurance)"
    # label variable v146d    "Outside funding: CS Social Security fund"
    # label variable v146e    "Outside funding: CS Reimbursement by employer"
    # label variable v146f    "Outside funding: CS Govt. contribution to private"
    # label variable v146g    "Outside funding: CS Donor agencies/ NGOs"
    # label variable v146h    "Outside funding: CS Faith-based programs"
    # label variable v146i    "Outside funding: CS Community programs"
    # label variable v146j    "Outside funding: CS Internal revenue/ collecting user fee from clients"
    # label variable v146x    "Outside funding: Other"
    # label variable v146y    "Outside funding: None"
    # label variable v146z    "NA - Outside funding: Don't know"
    
    FCdata$funding_moh <- ifelse(FCdata$v146a %in% 1, 1, 0)
    FCdata$funding_otherPub <- ifelse(FCdata$v146b %in% 1,1, 0)
    FCdata$funding_insurance <- ifelse(FCdata$v146c %in% 1,1, 0)
    FCdata$funding_socialSecurity <- ifelse(FCdata$v146d %in% 1,1, 0)
    FCdata$funding_employer <- ifelse(FCdata$v146e %in% 1,1, 0)
    FCdata$funding_gov2pvt <- ifelse(FCdata$v146f %in% 1,1, 0)
    FCdata$funding_donorNGO <- ifelse(FCdata$v146g %in% 1,1, 0)
    FCdata$funding_faith <- ifelse(FCdata$v146h %in% 1,1, 0)
    FCdata$funding_community <- ifelse(FCdata$v146i %in% 1,1, 0)
    FCdata$funding_userFees <- ifelse(FCdata$v146j %in% 1,1, 0)
    FCdata$funding_other <- ifelse(FCdata$v146x %in% 1,1, 0)
    # any funding
    FCdata$funding_any <- ifelse(FCdata$v146y %in% 0,1, 0)
    
  } else if (FCdata$v000[[1]] %in% "HT7") {
    
    # label variable v146a    "CS - Outside funding: Ministry of Health"
    # label variable v146b    "CS - Outside funding: Other public ministries"
    # label variable v146c    "CS - Outside funding: Medical schemes (insurance)"
    # label variable v146d    "CS - Outside funding: Social Security fund"
    # label variable v146e    "CS - Outside funding: Reimbursement by employer"
    # label variable v146f    "CS - Outside funding: Govt. contribution to private"
    # label variable v146g    "CS - Outside funding: Donor agencies/ NGOs"
    # label variable v146h    "CS - Outside funding: Faith-based programs"
    # label variable v146i    "CS - Outside funding: Community programs"
    # label variable v146j    "CS - Outside funding: Bilateral cooperation"
    # label variable v146k    "CS - Outside funding: Multilateral cooperation"
    # label variable v146l    "CS - Outside funding: Direct payment by the customer"
    # label variable v146m    "CS - Outside funding: International organization"
    # label variable v146x    "Outside funding: Other"
    # label variable v146y    "Outside funding: None"
    # label variable v146z    "NA - Outside funding: Don't know"
    
    FCdata$funding_moh <- ifelse(FCdata$v146a %in% 1, 1, 0)
    FCdata$funding_otherPub <- ifelse(FCdata$v146b %in% 1,1, 0)
    FCdata$funding_insurance <- ifelse(FCdata$v146c %in% 1,1, 0)
    FCdata$funding_socialSecurity <- ifelse(FCdata$v146d %in% 1,1, 0)
    FCdata$funding_employer <- ifelse(FCdata$v146e %in% 1,1, 0)
    FCdata$funding_gov2pvt <- ifelse(FCdata$v146f %in% 1,1, 0)
    FCdata$funding_donorNGO <- ifelse(FCdata$v146g %in% 1,1, 0)
    FCdata$funding_faith <- ifelse(FCdata$v146h %in% 1,1, 0)
    FCdata$funding_community <- ifelse(FCdata$v146i %in% 1,1, 0)
    FCdata$funding_bilateral <- ifelse(FCdata$v146j %in% 1,1, 0)
    FCdata$funding_multilateral <- ifelse(FCdata$v146k %in% 1,1, 0)
    FCdata$funding_userFees <- ifelse(FCdata$v146l %in% 1,1, 0)
    FCdata$funding_iNGO <- ifelse(FCdata$v146m %in% 1,1, 0)
    FCdata$funding_other <- ifelse(FCdata$v146x %in% 1,1, 0)
    # any funding
    FCdata$funding_any <- ifelse(FCdata$v146y %in% 0,1, 0)
    
  } else if (FCdata$v000[[1]] %in% "NM09") {
    
    # label variable v146a    "Outside funding:CS Faith-based/mission/churches"
    # label variable v146b    "Outside funding:CS Reimbursement by employer"
    # label variable v146c    "Outside funding:CS IInsurance"
    # label variable v146d    "Outside funding:CS MoHSS" MINISTRY OF HEALTH AND SOCIAL SERVICES
    # label variable v146e    "Outside funding:CS Other public ministries"
    # label variable v146f    "Outside funding:CS Social Security Fund"
    # label variable v146g    "Outside funding:CS Govt contribution to Private (NFP)"
    # label variable v146h    "Outside funding:CS User fees/ out-of-pocket (direct charge)"
    # label variable v146i    "Outside funding:CS Donor Agencies/NGOs (secular)"
    # label variable v146j    "Outside funding:CS Community programs"
    # label variable v146k    "Outside funding:CS Ministry of Defense"
    # label variable v146x    "Outside funding:Other"
    
    FCdata$funding_faith <- ifelse(FCdata$v146a %in% 1, 1, 0)
    FCdata$funding_employer <- ifelse(FCdata$v146b %in% 1,1, 0)
    FCdata$funding_insurance <- ifelse(FCdata$v146c %in% 1,1, 0)
    FCdata$funding_moh <- ifelse(FCdata$v146d %in% 1,1, 0)
    FCdata$funding_otherPub <- ifelse(FCdata$v146e %in% 1,1, 0)
    FCdata$funding_socialSecurity <- ifelse(FCdata$v146f %in% 1,1, 0)
    FCdata$funding_gov2pvt <- ifelse(FCdata$v146g %in% 1,1, 0)
    FCdata$funding_userFees <- ifelse(FCdata$v146h %in% 1,1, 0)
    FCdata$funding_donorNGO <- ifelse(FCdata$v146i %in% 1,1, 0)
    FCdata$funding_community <- ifelse(FCdata$v146j %in% 1,1, 0)
    FCdata$funding_MOD <- ifelse(FCdata$v146k %in% 1,1, 0)
    FCdata$funding_other <- ifelse(FCdata$v146x %in% 1,1, 0)
    # any funding
    FCdata$funding_any <- ifelse(FCdata$v146y %in% 0,1, 0)
    
  } else if (FCdata$v000[[1]] %in% "NP8") {
    
    # label variable v146a    "Outside funding:Ministry of health and population - CS"
    # label variable v146b    "Outside funding:Ministry of federal affairs and general admin federal-CS"
    # label variable v146c    "Outside funding:Ministry of social development at province - CS"
    # label variable v146d    "Outside funding:Local level - CS"
    # label variable v146e    "Outside funding:Service charge - CS"
    # label variable v146f    "Outside funding:Training colleges (nursing, medical) - CS"
    # label variable v146g    "Outside funding:Overhead from health insurance - CS"
    # label variable v146h    "NA - Outside funding:CS"
    # label variable v146i    "NA - Outside funding:CS"
    # label variable v146x    "Outside funding:Other"
    # label variable v146y    "Outside funding:None"
    # label variable v146z    "Outside funding:Don't know"
    # label variable v146ab   "Outside funding in NRs.:Ministry of health and population - CS"
    # label variable v146bb   "Outside funding in NRs.:Ministry of federal affairs and general admin federal - "
    # label variable v146cb   "Outside funding in NRs.:Ministry of social development at province - CS"
    # label variable v146db   "Outside funding in NRs.: local level - CS"
    # label variable v146eb   "Outside funding in NRs.: Service charge - CS"
    # label variable v146fb   "Outside funding in NRs.: Training colleges (nursing, medical) - CS"
    # label variable v146gb   "Outside funding in NRs.: Overhead from health insurance - CS"
    # label variable v146xb   "Outside funding in NRs.:Other sources - CS"
    
    FCdata$funding_moh <- ifelse(FCdata$v146a %in% 1, 1, 0)
    FCdata$funding_mofagaf <- ifelse(FCdata$v146b %in% 1,1, 0)
    FCdata$funding_mosdp <- ifelse(FCdata$v146c %in% 1,1, 0)
    FCdata$funding_community <- ifelse(FCdata$v146d %in% 1,1, 0)
    FCdata$funding_userFees <- ifelse(FCdata$v146e %in% 1,1, 0)
    FCdata$funding_trainingColleges <- ifelse(FCdata$v146f %in% 1,1, 0)
    FCdata$funding_insurance <- ifelse(FCdata$v146g %in% 1,1, 0)
    FCdata$funding_other <- ifelse(FCdata$v146x %in% 1,1, 0)
    # any funding
    FCdata$funding_any <- ifelse(FCdata$v146y %in% 0,1, 0)
    
    
  # } else if (FCdata$v000[[1]] %in% "SN6") {
    
    # label variable v146a    "Outside funding:CS"
    # label variable v146b    "Outside funding:CS"
    # label variable v146c    "Outside funding:CS"
    # label variable v146d    "Outside funding:CS"
    # label variable v146e    "Outside funding:CS"
    # label variable v146f    "Outside funding:CS"
    # label variable v146g    "Outside funding:CS"
    # label variable v146h    "Outside funding:CS"
    # label variable v146i    "Outside funding:CS"
    # label variable v146x    "Outside funding:Other"
    # label variable v146y    "Outside funding:None"
    # label variable v146z    "Outside funding:Don't know"
    
    
    
  } else if (FCdata$v000[[1]] %in% "TZ7") {
    
    # label variable v146a    "Outside funding:CS Ministry of Health"
    # label variable v146b    "Outside funding:CS Other public ministries"
    # label variable v146c    "Outside funding:CS Medical schemes (insurance)"
    # label variable v146d    "Outside funding:CS Social Security fund"
    # label variable v146e    "Outside funding:CS Reimbursement by employer"
    # label variable v146f    "Outside funding:CS Govt. contribution to private"
    # label variable v146g    "Outside funding:CS Donor agencies/ NGOs"
    # label variable v146h    "Outside funding:CS Faith-based programs"
    # label variable v146i    "Outside funding:CS Community programs"
    # label variable v146x    "Outside funding:Other"
    # label variable v146y    "Outside funding:None"
    # label variable v146z    "Outside funding:Don't know"
    
    
    FCdata$funding_moh <- ifelse(FCdata$v146a %in% 1, 1, 0)
    FCdata$funding_otherPub <- ifelse(FCdata$v146b %in% 1,1, 0)
    FCdata$funding_insurance <- ifelse(FCdata$v146c %in% 1,1, 0)
    FCdata$funding_socialSecurity <- ifelse(FCdata$v146d %in% 1,1, 0)
    FCdata$funding_employer <- ifelse(FCdata$v146e %in% 1,1, 0)
    FCdata$funding_gov2pvt <- ifelse(FCdata$v146f %in% 1,1, 0)
    FCdata$funding_donorNGO <- ifelse(FCdata$v146g %in% 1,1, 0)
    FCdata$funding_faith <- ifelse(FCdata$v146h %in% 1,1, 0)
    FCdata$funding_community <- ifelse(FCdata$v146i %in% 1,1, 0)
    FCdata$funding_other <- ifelse(FCdata$v146x %in% 1,1, 0)
    # any funding
    FCdata$funding_any <- ifelse(FCdata$v146y %in% 0,1, 0)
    
    FCdata$funding_userFees <- NA
    
    
    
  } else {
    
    stop(paste0("Warning: the function cleanFC_fundingSrc() has not been customized for ", FCdata$v000[[1]] %in% "TZ7", "."))
    
  }
  
  
  ## --------------------------------------------
  ## HARMONIZE to 4 buckets (non-exclusive):
  ##   funding_h_public, funding_h_private, funding_h_nonstate, funding_h_other
  ##   (plus funding_h_none, funding_h_dk, funding_h_any)
  ## --------------------------------------------
  
  # helpers
  .has_cols <- function(df, cols) intersect(cols, names(df))
  .any1 <- function(df, cols) {
    cns <- .has_cols(df, cols)
    if (length(cns) == 0) return(rep(0L, nrow(df)))
    as.integer(rowSums(df[, cns, drop = FALSE], na.rm = TRUE) > 0)
  }
  
  # normalize None / DK / Any (if questionnaire vars present)
  FCdata$funding_h_none <- ifelse("v146y" %in% names(FCdata), as.integer(FCdata$v146y %in% 1), 0L)
  FCdata$funding_h_dk   <- ifelse("v146z" %in% names(FCdata), as.integer(FCdata$v146z %in% 1), 0L)
  FCdata$funding_h_any  <- as.integer(FCdata$funding_h_none == 0)
  
  # country nuance for harmonization only (doesn't change your source flags)
  # NP8: local level (v146d) is public/local government
  if (identical(FCdata$v000[[1]], "NP8")) {
    FCdata$funding_localGov <- ifelse("v146d" %in% names(FCdata), as.integer(FCdata$v146d %in% 1), 0L)
  }
  
  FCdata$funding_none <- ifelse(FCdata$funding_any %in% 0, 1, 0)
  
  # ---- 4 bucket column groups ----
  
  # PUBLIC (direct government & public funds)
  .public_cols <- c(
    "funding_moh", "funding_mohss",            # MoH variants
    "funding_otherPub", "funding_MOD",         # other ministries (incl. Defense)
    "funding_mofagaf", "funding_mosdp",        # Nepal federal/province
    "funding_localGov",                        # NP8 local gov
    "funding_socialSecurity",                  # public social security funds
    "funding_gov2pvt"                          # government subsidies to private/NFP
  )
  
  # PRIVATE (private third-party & OOP)
  .private_cols <- c(
    "funding_insurance",                       # medical schemes/insurance
    "funding_employer"                        # employer reimbursement
  )
  
  # USER FEES (if applicable)
  .userFee_cols <- c(
    "funding_userFees"
    )                         # user fees / internal revenue / service charge
  
  # NON-STATE (external to government)
  # includes donors/INGOs, faith-based, community, training colleges, bilateral & multilateral
  .nonstate_cols <- c(
    "funding_donorNGO", "funding_iNGO",
    "funding_faith",
    "funding_community", "funding_trainingColleges",
    "funding_bilateral", "funding_multilateral"
  )
  
  # OTHER (specified "other" catch-all; keep DK separately above)
  .other_cols <- c("funding_other")
  
  # ---- build 5 buckets ----
  FCdata$funding_h_public   <- .any1(FCdata, .public_cols)
  FCdata$funding_h_private  <- .any1(FCdata, .private_cols)
  FCdata$funding_h_nonstate <- .any1(FCdata, .nonstate_cols)
  FCdata$funding_h_userFees <- .any1(FCdata, .userFee_cols)
  FCdata$funding_h_other    <- .any1(FCdata, .other_cols)
  
  
  return(FCdata)
  
  
}


